# ===== MongoDB Atlas Configuration =====
spring.data.mongodb.uri=mongodb+srv://canteen_admin:%23Vimal2004@canteenmgmt.jxhwlf1.mongodb.net/?appName=CanteenMgmt
spring.data.mongodb.database=canteendb

# ===== Server Configuration =====
server.port=8081

# ===== JWT Configuration =====
jwt.secret=MyCanteenSuperSecretKeyThatIsAtLeast256BitsLongForHS256Algorithm2024
jwt.expiration=86400000

# ===== CORS =====
spring.web.cors.allowed-origins=http://localhost:5173

# ===== Application =====
spring.application.name=CanteenMgmt
